// src/components/Particles/items/StarItemParticle.jsx
import React, { useEffect, useRef } from "react";
import { useLoader, useFrame } from "@react-three/fiber";
import * as THREE from "three";

export const StarItemParticle = ({ position, item, timeModifier, color }) => {
  const texture = useLoader(THREE.TextureLoader, "./particles/star_coin.png");
  const pointsRef = useRef();
  const materialRef = useRef();
  const sizeRef = useRef(1);
  const opacityRef = useRef(1);
  const originalYpos = useRef(0);

  const points = React.useMemo(() => {
    const geom = new THREE.BufferGeometry();
    geom.setAttribute(
      "position",
      new THREE.Float32BufferAttribute(position, 3)
    );
    return geom;
  }, [position]);

  useEffect(() => {
    if (materialRef.current) {
      materialRef.current.color.multiplyScalar(6);
    }
  }, []);

  useEffect(() => {
    if(item){
      sizeRef.current = 0;
      opacityRef.current = 1;
      pointsRef.current.position.x = Math.random() * 1 - 0.5;
      pointsRef.current.position.y = Math.random() * 0.5 - 0.25;
      originalYpos.current = pointsRef.current.position.y;
    }
  }, [item]);

  useFrame((state, delta) => {
    const time = state.clock.getElapsedTime();
    pointsRef.current.position.y += 0.008 * delta * 144;
    if (sizeRef.current < 1) {
      sizeRef.current = Math.min(sizeRef.current + 0.01 * delta * 144, 1);
    }

    if (pointsRef.current.position.y > originalYpos.current + 0.01) {
      opacityRef.current = Math.max(opacityRef.current - 0.01 * delta * 144, 0);
    } else {
      opacityRef.current = Math.abs(Math.sin(time * timeModifier * 1500));
    }

    // Update material properties directly
    if (materialRef.current) {
      materialRef.current.size = sizeRef.current;
      materialRef.current.opacity = opacityRef.current;
    }
});

  return (
    <points ref={pointsRef} geometry={points}>
      <pointsMaterial
        ref={materialRef}
        alphaMap={texture}
        transparent={true}
        depthWrite={false}
        toneMapped={false}
        color={color}
      />
    </points>
  );
};

// src/components/Particles/items/StarItemParticle.svelte
<script lang="ts">
  import { T, useTask } from '@threlte/core'
  import { useTexture } from '@threlte/extras'
  import * as THREE from 'three'

  let { position, item, timeModifier, color } = $props();

  const texture = useTexture('./particles/star_coin.png');
  let pointsRef = $state<THREE.Points>();
  let materialRef = $state<THREE.PointsMaterial>();
  let size = 1;
  let opacity = 1;
  let originalYpos = 0;
  let time = 0;

  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute('position', new THREE.Float32BufferAttribute(position, 3));

  $effect(() => {
    if (materialRef) {
      materialRef.color.multiplyScalar(6);
    }
  });

  $effect(() => {
    if (item && pointsRef) {
        size = 0;
        opacity = 1;
        pointsRef.position.x = Math.random() * 1 - 0.5;
        pointsRef.position.y = Math.random() * 0.5 - 0.25;
        originalYpos = pointsRef.position.y;
    }
  });

  useTask((delta) => {
    if (!pointsRef || !materialRef) return;
    time += delta;

    pointsRef.position.y += 0.008 * delta * 144;
    
    if (size < 1) {
      size = Math.min(size + 0.01 * delta * 144, 1);
    }

    if (pointsRef.position.y > originalYpos + 0.01) {
      opacity = Math.max(opacity - 0.01 * delta * 144, 0);
    } else {
      opacity = Math.abs(Math.sin(time * timeModifier * 20)); // Adjusted speed estimation
    }

    materialRef.size = size;
    materialRef.opacity = opacity;
  });
</script>

{#if $texture}
    <T.Points bind:ref={pointsRef} {geometry}>
        <T.PointsMaterial
            bind:ref={materialRef}
            alphaMap={$texture}
            transparent={true}
            depthWrite={false}
            toneMapped={false}
            {color}
        />
    </T.Points>
{/if}
