// src/components/Ground.jsx
import { RigidBody } from '@react-three/rapier'

export const Ground = (props) => {
  return (
    <RigidBody
      type='fixed'
      {...props}
    >
      <mesh
        transparent
        receiveShadow
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <planeGeometry args={[1000, 1000, 1000]} />
        <meshStandardMaterial
          color='yellow'
          opacity={0}
          transparent
        />
      </mesh>
    </RigidBody>
  )
}

// src/components/Ground.svelte
<script lang="ts">
    import { T } from "@threlte/core";
    import { RigidBody } from "@threlte/rapier";

    let { ...props } = $props();
</script>

<RigidBody type="fixed" {...props}>
    <T.Mesh receiveShadow rotation={[-Math.PI / 2, 0, 0]}>
        <T.PlaneGeometry args={[1000, 1000, 1000]} />
        <T.MeshStandardMaterial color="yellow" opacity={0} transparent />
    </T.Mesh>
</RigidBody>
