// src/components/Particles/smoke/SmokeParticle.svelte
<script lang="ts">
  import { T, useTask } from '@threlte/core'
  import { useTexture } from '@threlte/extras'
  import * as THREE from 'three'

  let { position, png, leftDrift, rightDrift, delay = 0 } = $props();

  const texture = useTexture(png);
  let pointsRef = $state<THREE.Points>();
  let initialized = false;

  const geometry = new THREE.BufferGeometry();
  geometry.setAttribute('position', new THREE.Float32BufferAttribute(position, 3));

  $effect(() => {
    const timer = setTimeout(() => {
      initialized = true;
    }, delay);
    return () => clearTimeout(timer);
  });

  useTask((delta) => {
    if (!initialized || !pointsRef) return;

    if(leftDrift || rightDrift){
      pointsRef.position.z += 0.1 * delta * 144;
      const material = pointsRef.material as THREE.PointsMaterial;

      //Set inclination
      if(leftDrift){
        pointsRef.position.x -= 0.09 * delta * 144;
      }

      if(rightDrift){
        pointsRef.position.x += 0.09 * delta * 144;
      }

      if(pointsRef.position.x < -1.8 || pointsRef.position.x > 1.8) {
        pointsRef.position.z = 0;
        pointsRef.position.x = 0;
        material.opacity = 1.5;
        material.size = 4;
      }
    
      if(material.opacity > 0) {
        material.opacity -= 0.01 * delta * 144;
      }

      if(material.size > 0) {
        //Shrinking effect
        material.size -= 0.1* delta * 144;
      }

    } else {
      pointsRef.position.z = 0;
      pointsRef.position.x = 0;
      const material = pointsRef.material as THREE.PointsMaterial;
      material.opacity = 0;
      material.size = 0;
    }
  });
</script>

{#if $texture}
    <T.Points bind:ref={pointsRef} {geometry}>
        <T.PointsMaterial
            size={1}
            alphaMap={$texture}
            transparent={true}
            depthWrite={false}
            color={0xBFBFBF}
            opacity={1}
            toneMapped={false}
        />
    </T.Points>
{/if}

// src/components/Particles/smoke/SmokeParticle.jsx
import React, { useRef, useMemo } from "react";
import { useLoader, useFrame } from "@react-three/fiber";
import * as THREE from "three";

export const SmokeParticle = ({ position, png, leftDrift, rightDrift, delay = 0 }) => {
  const texture = useLoader(THREE.TextureLoader, png);
  const pointsRef = useRef();
  const initialized = useRef(false);

  // Initialize after delay
  useMemo(() => {
    const timer = setTimeout(() => {
      initialized.current = true;
    }, delay);
    return () => clearTimeout(timer);
  }, [delay]);

  const points = useMemo(() => {
    const geom = new THREE.BufferGeometry();
    geom.setAttribute(
      "position",
      new THREE.Float32BufferAttribute(position, 3)
    );
    return geom;
  }, [position]);

  useFrame(({clock}, delta) => {
    if (!initialized.current) return;

    const pointsCurrent = pointsRef.current;

    if(leftDrift || rightDrift){
      pointsCurrent.position.z += 0.1 * delta * 144;

      //Set inclination
      if(leftDrift){
        pointsCurrent.position.x -= 0.09 * delta * 144;
      }

      if(rightDrift){
        pointsCurrent.position.x += 0.09 * delta * 144;
      }

      if(pointsCurrent.position.x < -1.8 || pointsCurrent.position.x > 1.8) {
        pointsCurrent.position.z = 0;
        pointsCurrent.position.x = 0;
        pointsCurrent.material.opacity = 1.5;
        pointsCurrent.material.size = 4;
      }
    
      if(pointsCurrent.material.opacity > 0) {
        pointsCurrent.material.opacity -= 0.01 * delta * 144;
      }

      if(pointsCurrent.material.size > 0) {
        //Shrinking effect
        pointsCurrent.material.size -= 0.1* delta * 144;
      }

    } else {
      pointsCurrent.position.z = 0;
      pointsCurrent.position.x = 0;
      pointsCurrent.material.opacity = 0;
      pointsCurrent.material.size = 0;
    }

  });

  return (
    <points ref={pointsRef} geometry={points}>
      <pointsMaterial
        size={1}
        alphaMap={texture}
        transparent={true}
        depthWrite={false}
        color={0xBFBFBF}
        opacity={1}
        toneMapped={false}
      />
    </points>
  );
};
